# Block enderpearls older than a certain age while in combat.
prevent-stasis: true

# Age of enderpearls that will be blocked while in combat, in ticks. 20 ticks = 1 second.
# Default: 300 (ticks)
stasis-enderpearl-age: 300

# Messages that will be sent to players after an enderpearl teleport is blocked.
messages:  # Use {age} to include the enderpearl age in ticks in the message.
  blocked: "§cYou cannot teleport with an enderpearl older than {age} ticks while in combat."