# Block enderpearl teleports longer than a specified distance while in combat. Default: true
prevent-distant-enderpearl: true

# How far a player can travel with an enderpearl while in combat before being blocked. Has no effect if prevent-distant-enderpearl is false.
# Nether coordinates will be converted to overworld coordinates for distance calculation.
# Default: 300 (blocks)
max-enderpearl-distance: 300

# Messages that will be sent to players after an enderpearl teleport is blocked by the stasis expansion.
messages:  # Use {distance} to include the teleport distance in the message.
  distance-blocked: "§cYou cannot teleport with an enderpearl more than {distance} blocks while in combat."